### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Anshkumardev** [INFO526-DataViz/project-01-ggplotGurus#1]
---
name: Proposal peer review
about: Peer review of project proposal
title: Proposal peer review
labels: ''
assignees: ''
---

The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- [Sai Madhuri Kandula] - @[ksmadhuri]
- [Priyarsha Vallabhaneni] - @[Priyarsha31]
- [Ansh Kumar Dev] - @[Anshkumardev]
- [jothish Kumar Polaki] - @[Jothish21]
- ...

- Describe the goal of the project.

The project's objective is to evaluate the precision of weather forecasts in the United States, utilizing data from the USA National Weather Service. It has two main goals:

Evaluate temperature prediction inaccuracies throughout the United States and recognize groups of cities with comparable error tendencies.

Investigate the seasonal fluctuations in temperature forecast errors across diverse U.S. regions and represent these variances using a heatmap.

In essence, the project aspires to advance our comprehension of weather forecast accuracy by conducting data analysis and visualization to deliver meaningful insights.

- Describe the data used or collected.

The data used for this project is obtained from the USA National Weather Service and includes three main datasets:

Weather Forecasts Dataset: It contains information about 167 U.S. cities, including temperature forecasts, forecast outlooks, and other relevant data.

Cities Dataset: This dataset provides geographic details for the 167 cities, including latitude, longitude, and climate information.

Outlook Meanings Dataset: It offers descriptions for the forecast outlooks mentioned in the Weather Forecasts dataset.

These datasets cover a 16-month period and serve as the foundation for analyzing weather forecast accuracy across the United States and throughout different seasons.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

For Question 1, the project team plans to utilize the Weather Forecasts dataset to calculate temperature forecasting errors. Cities will be categorized by state, and an interactive choropleth map of the United States will be created to display these errors. The team will implement a dark mode design for aesthetics and allow users to zoom in for detailed exploration.

Regarding Question 2, the team intends to transform the data for seasonal analysis, calculating seasonal temperature errors. Heatmaps overlaid on a U.S. map will be generated to visualize seasonal variations in forecasting errors.

In summary, the project aims to analyze temperature forecast accuracy and seasonal variations using interactive maps, offering valuable insights to users.

- Is there anything that is unclear from the proposal?

It might be beneficial to briefly mention the source of the data and any potential limitations or data cleaning steps that might be required.

- Provide constructive feedback on how the team might be able to improve their project.

Ensure precise data transformation and calculations for creating essential variables like "season" and "temp_error" as indicated in the code blocks, maintaining accuracy throughout the analysis process.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We are particularly interested in the interactive capabilities of the plot, as highlighted in the proposal, including the implementation of a zoom feature for enhanced user engagement.

- Provide constructive feedback on any issues with file and/or code organization.

We have identified text within a code block that may require refinement and correction.

- (Optional) Any further comments or feedback?

**Comment by SwethaSiripurapuu** [comment]
Hello Team,

Thank you for your feedback! we have made the changes and pushed the updated proposal to the repo.

Thank you and good luck!
