### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Swati09Das** [INFO526-DataViz/project-01-ggplotGurus#2]
The following is the peer review of the project proposal by DataInk Drinkers. The team members that participated in this review are 

Swati Das - @Swati09Das
Tejashwini Kasa - @TejashwiniKasa
Partha Koundinya Panguluri - @partha-pkp
Chethana Thondebhavi Shantha Kumar - @Chethana-16

- Describe the goal of the project.

    - The goal of the project is to find weather forecast accuracy across the cities of US in different seasons.

- Describe the data used or collected.

   - The data contains 16 months of weather forecast and subsequent observations for 167 cities across US and it is divided into 3 sets namely weather_forecast, cities and outlook_meanings.   

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

    - In question 1, advanced geospatial data visualization techniques and dark mode design will be used. An interactive choropleth map of the US will be displayed to show the temperature error in the cities.
    - In question 2, a geographical heatmap will be presented using the latitude and longitude data to exhibit seasonal variations in temperature forecast errors.

- Is there anything that is unclear from the proposal?
 
    - Both the questions convey very similar meaning, which make them difficult to distinguish.
    - The `proposal.qmd` file does not contain the code for loading the dataset.
    - The analysis section has been divided into 2 parts to explain both the questions but it is not presented in a proper way. This makes flow of the analysis section in the proposal confusing.

- Provide constructive feedback on how the team might be able to improve their project.

    - There is not much difference in question 1 and 2 visualizations. If possible, please use different concepts for either of the questions.
     - Please make sure to maintain a proper proportion of content for the explanation of dataset and the reason of choosing the dataset (The reasoning part is lengthy).
     - Please maintain the proper flow of the content with appropriate styles of headings (Question 2 is in bold, analysis heading is in in-correct order).

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

    - The heat map of the temperature error across the US cities during the different seasons will be an interesting visualization.

- Provide constructive feedback on any issues with file and/or code organization.

    - The overall objective seems nice.
    - Please ensure to load the dataset in `proposal.qmd` file and have the code for same.
 
- (Optional) Any further comments or feedback?
    
    - Looking forward to see the final outcome. All the best!!! 
                ~~~ From,
                            Team DataInk Drinkers

**Comment by SwethaSiripurapuu** [comment]
Hello Team, Thank you for your feedback. 

We would like to emphasize that both our questions solve different concerns.

For Question 1, It specifically examines the spatial distribution of temperature forecasting errors across the entirety of the U.S. When regions with similar forecasting error profiles are identified, meteorological agencies can implement targeted model refinements and resource allocations, ensuring that areas with notable discrepancies receive the necessary attention. 

In contrast, Question 2 employs a heatmap to spotlight seasonal variations in forecasting errors. This offers a temporal perspective, enabling agencies to understand and tackle challenges specific to different seasons.

Let us know if you have any questions. 

Thank you,
~ggplotgurus
