### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-01-ggplotGurus#3]
Dear ggplotGurus: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |       3 |
| Proposal | 5         |        4|
| Workflow | 1         |        1|
| Teamwork | 1         |        1|
| Total    | 10        |        9|

Your plan is sound as well. Great work!
A couple minor issues to fix: 
1. Always give units for temperature
2. "Begin by segregating the data season-wise." The correct grammar is seasonally. 
3. State the data types for the columns you are using.

**Comment by SwethaSiripurapuu** [comment]
Hello Professor, Thank You for the feedback. We have updated the code accordingly.

**Comment by Gchism94** [comment]
Looks good, your final grade for the proposal is 9.5/10.
