### ISSUE TITLE
Write-up feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-01-ggplotGurus#7]
Dear ggplotGurus: Below is the score breakdown for your write-up. 

## Write-up

|          | Available | Earned |
|----------|-----------|--------|
| Introduction     | 2         |    1.5    |
| Justification of approach | 6 (3/Question)         |   6     |
| Code | 6 (3/Question)         |   6     |
| Visualization | 8 (4/Question)         |    8    |
| Discussion | 8 (4/Question) |  8 |
| Total    | 30        |   29.5     |

Feedback: 
Ovrall, very nice! Just one minor nitpick issue (below) 
Introduction - the intro should be 1-2 paragraphs. Some code formatting would have helped for the `columns`.

**Comment by shalonwalter** [comment]
here the earned would be 29.5

**Comment by SwethaSiripurapuu** [comment]
Hello Professor fixed the introduction now. Thanks.
